### PR TITLE
Allow for Camera selection over NetworkTables

### PR DESCRIPTION
**Pull request by AustinShalit**
This is broken right now.  For some reason,`immediateNotify` does not do what I think it does.

@PeterJohnson

### CODE REVIEW

**Comment by AustinShalit** [comment]
Actually, I think I know what I did.

**Comment by PeterJohnson** [comment]
I think you need to use getTable("") instead of getTable("/").  The two are not equivalent.

**Comment by AustinShalit** [comment]
😄 All good now

**Comment by AustinShalit** [comment]
Code to test:
```
UsbCamera c1 = CameraServer.getInstance().startAutomaticCapture(0);
		UsbCamera c2 = CameraServer.getInstance().startAutomaticCapture(1);
		
		while (true) {
			try {
				NetworkTable.getTable("").putString("CameraSelection", c1.getName());
				Thread.sleep(5000);
				NetworkTable.getTable("").putString("CameraSelection", c2.getName());
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
```

**Comment by pzcode** [comment]
Does this help with switching the camera to be displayed on SmartDashboard?

**Comment by AustinShalit** [comment]
Yes, SmartDashboard will now look at a provided NetworkTable key to choose the camera to display.

**Pull request merged**
