### PR TITLE
Bug fixes including choosers that don't appear and livewindow widgets that don't appear.

### LINKED ISSUE #184: SmartDashboard does not support several LiveWindow types
LiveWindow types used in our robot code that are not supported by SmartDashboard:

- CANCoder
- AbsoluteEncoder
- Duty Cycle
Additional Sendables that are not supported (from code inspection):
- AnalogOutput
- External Directory Counter
- Differential Drive
- Mechanum Drive
- Nider Brushless
- PWM
- Field2d
- Mechanism2d

These are missing entirely (no NamedDataType and no livewindow element). 
Also, Scheduler looks like it should be supported but I am seeing an error being thrown when the Scheduler subtable within the LiveWindow table is processed. Investigation shows that this is due to missing registration of the Scheduler element which looks easy to fix.

Initially I thought that adding support in SmartDashboard for  the missing elements would be way to go. However, SmartDashboard's automatic layout capability is really weak, esp. for livewindow elements and I wonder whether it is actually useful anymore when glass is available which does so much better.

Now I think the better course is simply to change SmartDashboard so it gracefully handles NT entries for which it doesn't have gui elements -- instead of getting uncaught null pointer errors, which occur in threads where they seem not cause actual problems, detect that there is no element and do nothing.

Advice welcomed!

### LINKED ISSUE #188: Cancel command button in the Scheduler Widget cancels the command forever
The Cancel buttons in the Scheduler widget post the ids of commands to be cancelled as a Double[] value with key "Cancel". The expectation is that upon noticing the request to cancel the robot-side Scheduler sendable will set the value for the "Cancel" key back to the empty list. 
Unfortunately the "setting back to the empty list" doesn't work because the sendable tries to set it to an empty Long[] but it already has type Double[]. The result is that commands that have been cancelled once are cancelled whenever they run, forever.
Since NetworkTables version 3 only supports Double as the over-the-wire numeric type there doesn't seem to be any hope for fixing this purely in SmartDashboard code as long as SD uses NT3.

### PR DESCRIPTION
**Pull request by chauser**
Several significant changes and two rather cosmetic changes.
Significant changes:

- Arranged that connection to the robot always occurs after processing the save file. Fixes the problem that Choosers don't show up if connection to the robot happens before a chooser in the save file is processed. Also probably related to issue #81 which mentions the same problem with buttons.
- Add LiveWindow widgets to containing subsystem widget when creating them from the save file. Fixes issue #73.
- Registering the SchedulerType properly allows the Scheduler widget to be instantiated when the robot code places the Scheduler on SmartDashboard with `SmartDashboard.putData`.
- `NetworkTable.getTable` returns a new table with its own set of entries so it should only be called once per table. Changed Robot.java to implement this behavior. 
- Fix issue #187. Unfortunately I can't see any way to fix #188, given the way the WPILib Sendable for the Scheduler works on the robot and the limitations of NetworkTables version 3.

Cosmetic changes:

1. When SmartDashboard is run with its stdout/stderr visible it produces a lot of uncaught java error index errors and tracebacks for choosers before the set of choices has been loaded.
2. Similarly, when SmartDashboard does not have a LiveWindow widget for a device type (e.g. CANCoder and many others) it produces an uncaught null pointer error message and traceback.
Although these errors are uncaught, they occur on single-use callback threads so they don't actually keep SmartDashboard from operating, but they are a major distraction when trying to work on actual problems. Resolves #184; #97 is related in that it mentions the stacktraces for unimplemented device types but it asks to have them implemented.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
It feels like the disabling DS connection should be a separate PR, since that is a workaround that could hopefully be reenabled in the future.

**Comment by sciencewhiz** [comment]
It feels like disabling DS connection may also workaround #81

**Comment by chauser** [comment]
Yes. I've separated the DSClient change into a new branch and will make a new PR for it.

**Comment by chauser** [comment]
> Yes. I've separated the DSClient change into a new branch and will make a new PR for it.

Changes to DSClient are back in this PR but as a delay in starting the DSClient until after the save file is processed, rather than completely disabling it. I think this will be satisfactory in providing both automatic connection and resolving the issue of things not appearing.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
