### PR TITLE
Publish releases to GitHub from Travis

### LINKED ISSUE #8: Publish a Release
We should publish a release of SmartDashboard here on github.

### PR DESCRIPTION
**Pull request by AustinShalit**
closes #8

I need an admin to generate a key.

### CODE REVIEW

**Comment by 333fred** [comment]
Uh, you don't need to put the key in the file, right? If you do, there is no way I'll merge this.

**Comment by AustinShalit** [comment]
Take a look at this: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by 333fred** [comment]
I'm not a fan of this for one specific reason: there's no way to guarantee (with our current setup) of the travis-built version having the same version of ntcore as the jenkins built-version will have. since the official build will build ntcore just before building smartdashboard.

**Comment by 333fred** [comment]
We archive the jar on Jenkins: http://frcjenkins.wpi.edu/job/SmartDashboard/job/SmartDashboard%20-%20Release/lastSuccessfulBuild/artifact/smartdashboard/build/libs/smartdashboard-all.jar. Does adding a link to readme for that work for the issue?

**Comment by AustinShalit** [comment]
Sounds good.

**Pull request closed without merging**
